config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # ログアウト用のルートを設定する
  devise_scope :user do
    delete 'users/sign_out', to: 'devise/sessions#destroy', as: :custom_destroy_user_session
  end

  get 'comments/index'
  root 'comments#index'

  resources :events, only: %i[index new create update destroy edit]
  resources :user_comments, only: %i[create edit update destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    #belongs_to :user
    validates :user_id, {presence: true}

    def user
    #インスタンスメソッド内でselfはインスタンス自身を指す。
    return Post.find_by(id: self.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy


  def posts
    return Event.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all.order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(
      content: params[:content],
      user_id: @current_user.id
    )
    if @event.save
      redirect_to root_path, notice: "投稿が成功しました。"
    else
      flash.now[:alert] = "投稿ができませんでした。すまん"
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to root_path, notice: "投稿を更新しました"
    else
    render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path, notice: "投稿を削除しました"
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :tag , :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/comments/index.html.erb
<h1>ログインアプリ</h1>
<% if user_signed_in? %>
  <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
  <h4> メールアドレス： <%= current_user.email %> </h4>
  <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h2> 現在ログインしていません </h2>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
<% end %>

<!-- 掲示板一覧 -->
<div class="row">
  <div class="col-12">
    <div class="row">
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>本文</th>
      <th>日付</th>
      <th>タグ</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td class="table-cell"><%= event.title %></td>
        <td class="table-cell"><%= event.body %></td>
        <td class="table-cell"><%= event.date.strftime('%Y-%m-%d') %></td>
        <td class="table-cell"><%= event.tag %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "イベント作成", new_event_path, class: 'post' %>
<%= link_to "編集ボタン", new_event_path, class: 'post' %>
<%= link_to "削除ボタン", new_event_path, class: 'post' %>

app/views/events/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="event-id-<%= event.id %>">
    <div class="card">
      <%= image_tag 'app/assets/images/に配置した写真のデータ名', class: 'card-img-top', size: '300x200' %>
      <div class="card-body">
        <h4 class="card-title">
          <a href="#">
            <%= event.title %>
          </a>
        </h4>
        <div class='mr10 float-right'>
          <a href="#"><%= icon 'fas', 'trash', class: 'pr-1' %></a>
          <a href="#"><%= icon 'fa', 'pen' %></a>
        </div>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= icon 'far', 'user' %>
            <%= event.user.decorate.full_name %>
          </li>
          <li class="list-inline-item">
            <%= icon 'far', 'calendar' %>
            <%= l event.created_at, format: :long %>
          </li>
        </ul>
        <p class="card-text"><%= event.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>events#edit</h1>
<span>現在ログイン中のユーザー：<%= current_user.name %></span>
<%= form_for(@event, url: event_path(@event)) do |form| %>
    <div>
        <%= form.label :タイトル %><br>
        <%= form.text_field :title, autofocus: true, :placeholder =>"#{@event.title}" %>
    </div>
    <div>
        <%= form.label :中身 %><br>
        <%= form.text_area :body, :placeholder =>"#{@event.body}" %>
    </div>
    <div><%= form.submit "更新する" %></div>
<% end %>

app/views/events/new.html.erb
<h1>新規イベント作成</h1>
<%= form_for(@event) do |form| %>
  <div class="form-group">
    <%= form.label :タイトル %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :本文 %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :日付 %>
    <%= form.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :タグ %>
    <%= form.text_field :tag, class: "form-control" %>
  </div>

  <%= form.submit "作成", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groupen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <% if user_signed_in? %>
        <nav>
          <ul>
            <li>
              <%= link_to "Home", root_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, data:{ turbo_method: :delete } %>
            </li>
          </ul>
        </nav>
      <% else %>
        <nav>
          <ul>
            <li>
              <%= link_to "Home", root_path %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
          </ul>
        </nav>
      <% end %>
    </header>
    <main>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </main>
  </body>
</html>